name: Emscripten Build
on: [push, pull_request]

env:
  EM_VERSION: 2.0.25
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}

    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v10
      with:
        version: ${{ env.EM_VERSION }}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

    - name: Build
      run: |
        mkdir -p out/wasm
        cd out/wasm
        emcmake cmake -DCMAKE_BUILD_TYPE=MinSizeRel ../../
        make
        mkdir xsystem35
        mv src/xsystem35.* xsystem35/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: xsystem35-wasm
        path: out/wasm/xsystem35
